-- ========================================
-- HINTERGRÜNDE (BACKGROUNDS) DATENBANK
-- ========================================

INSERT INTO backgrounds (name_de, name_en, description_de, skill_proficiencies, tool_proficiencies, languages, equipment, feature_name_de, feature_description_de) VALUES

('Pirat', 'Pirate',
'Du hast dein Leben auf den Meeren verbracht, Schiffe überf allen und Schätze geplündert. Du kennst die Gesetze der See und die Freiheit des Piratenlebens.',
'["athletics", "perception"]',
'["navigators_tools", "vehicles_water"]',
0,
'[{"item": "Enterhaken", "quantity": 1}, {"item": "Seil (15m)", "quantity": 1}, {"item": "Glücksbringer", "quantity": 1}, {"item": "Normale Kleidung", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 10}]',
'Schlechter Ruf',
'Egal wo du hinkommst, die Leute fürchten dich aufgrund deines Rufs. In zivilisierten Siedlungen kannst du mit kleinen Vergehen davonkommen (wie das Nichtbezahlen von Essen), da die Leute dich nicht verärgern wollen. Allerdings wirst du auch öfter von Autoritäten beobachtet.'),

('Adliger', 'Noble',
'Du verstehst Reichtum, Macht und Privilegien. Du trägst einen Adelstitel und deine Familie besitzt Land, erhebt Steuern und übt politischen Einfluss aus.',
'["history", "persuasion"]',
'["gaming_set"]',
1,
'[{"item": "Feine Kleidung", "quantity": 1}, {"item": "Siegelring", "quantity": 1}, {"item": "Pergamentrolle mit Stammbaum", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 25}]',
'Privilegposition',
'Dank deiner adligen Geburt werden dich die Leute der gehobenen Gesellschaft respektieren. Du kannst eine Audienz bei einem lokalen Adligen sichern, wenn du sie brauchst.'),

('Gauner', 'Criminal',
'Du hast dein Leben im Schatten der Gesellschaft verbracht, Gesetze gebrochen und von kriminellen Aktivitäten gelebt.',
'["deception", "stealth"]',
'["thieves_tools", "gaming_set"]',
0,
'[{"item": "Brecheisen", "quantity": 1}, {"item": "Dunkle Kleidung mit Kapuze", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 15}]',
'Kriminelle Kontakte',
'Du hast einen zuverlässigen Kontakt, der als Verbindung zu einem Netzwerk anderer Krimineller dient. Du weißt, wie man Nachrichten über große Entfernungen an deinen Kontakt übermittelt.'),

('Volksheld', 'Folk Hero',
'Du stammst aus den einfachen Leuten, aber du bist zu einem Champion geworden. Die Menschen sehen in dir ihren Verfechter.',
'["animal_handling", "survival"]',
'["artisan_tools", "vehicles_land"]',
0,
'[{"item": "Handwerkzeug", "quantity": 1}, {"item": "Schaufel", "quantity": 1}, {"item": "Eisentopf", "quantity": 1}, {"item": "Normale Kleidung", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 10}]',
'Rustikale Gastfreundschaft',
'Einfache Leute helfen dir, wo sie können. Sie verstecken dich vor dem Gesetz, heilen deine Wunden oder teilen ihr bescheidenes Mahl mit dir.'),

('Gelehrter', 'Sage',
'Du hast Jahre damit verbracht, die Geheimnisse des Multiversums zu erforschen. Du hast an uralten Schriftrollen studiert und verbotenes Wissen gesucht.',
'["arcana", "history"]',
'[]',
2,
'[{"item": "Tintenflasche", "quantity": 1}, {"item": "Federkiel", "quantity": 1}, {"item": "Kleines Messer", "quantity": 1}, {"item": "Brief eines verstorbenen Kollegen", "quantity": 1}, {"item": "Normale Kleidung", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 10}]',
'Forscher',
'Wenn du versuchst, etwas zu lernen oder dich an ein Stück Wissen zu erinnern, kennst du normalerweise einen Ort oder eine Person, die die Antwort haben könnte (Bibliothek, Gelehrter, etc.).'),

('Soldat', 'Soldier',
'Du hast als Teil einer Armee trainiert und gekämpft. Krieg ist dein Handwerk und du kennst die Realität des Schlachtfelds.',
'["athletics", "intimidation"]',
'["gaming_set", "vehicles_land"]',
0,
'[{"item": "Rangabzeichen", "quantity": 1}, {"item": "Trophäe eines gefallenen Feindes", "quantity": 1}, {"item": "Würfelset oder Kartendeck", "quantity": 1}, {"item": "Normale Kleidung", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 10}]',
'Militärischer Rang',
'Du hast einen militärischen Rang von deiner Karriere als Soldat. Soldaten, die loyal zu deiner ehemaligen Armee sind, erkennen deine Autorität und deinen Einfluss an.'),

('Akolyth', 'Acolyte',
'Du hast dein Leben im Dienst eines Tempels für einen bestimmten Gott oder ein Pantheon verbracht.',
'["insight", "religion"]',
'[]',
2,
'[{"item": "Heiliges Symbol", "quantity": 1}, {"item": "Gebetbuch", "quantity": 1}, {"item": "Weihrauch", "quantity": 5}, {"item": "Priestergewand", "quantity": 1}, {"item": "Normale Kleidung", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 15}]',
'Zuflucht der Gläubigen',
'Du kannst magische Dienste für dich und deine Gefährten von einem Priester deines Glaubens kostenlos erhalten (nicht gold-kosten-intensiv). Tempel deiner Religion bieten dir Unterkunft.'),

('Unterhalter', 'Entertainer',
'Du bist es gewohnt, vor einem Publikum aufzutreten, sei es als Musiker, Schauspieler oder Geschichtenerzähler.',
'["acrobatics", "performance"]',
'["disguise_kit", "musical_instrument"]',
0,
'[{"item": "Musikinstrument", "quantity": 1}, {"item": "Liebesbriefe von Bewunderern", "quantity": 1}, {"item": "Kostüm", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 15}]',
'Bei Beliebtheit',
'Du kannst immer einen Ort finden, an dem du auftreten kannst (Tavernen, Theater, Zirkus). An solchen Orten erhältst du kostenlose Unterkunft und Verpflegung (bescheidener oder komfortabler Lebensstandard). Deine Auftritte machen dich lokal bekannt.'),

('Eremit', 'Hermit',
'Du hast in Abgeschiedenheit gelebt - entweder in einer geschützten Gemeinschaft oder völlig allein - für eine bedeutende Zeit deines Lebens.',
'["medicine", "religion"]',
'["herbalism_kit"]',
1,
'[{"item": "Schriftrolle mit Gebeten", "quantity": 1}, {"item": "Decke", "quantity": 1}, {"item": "Kräuterkundler-Set", "quantity": 1}, {"item": "Normale Kleidung", "quantity": 1}, {"item": "Geldbeutel", "quantity": 1, "gold": 5}]',
'Entdeckung',
'Die ruhige Abgeschiedenheit deines Rückzugsortes gab dir Zugang zu einer einzigartigen und mächtigen Entdeckung. Die genaue Natur dieser Offenbarung hängt von der Natur deiner Abgeschiedenheit ab.');
