-- Druiden Zauber Level 2 (Deutsch)
-- Basierend auf D&D 5e Regelwerk

INSERT INTO spells (name_de, name_en, level, class, school, ritual, casting_time, components, concentration, source, page_de, page_en, description_de, description_en, school_de, casting_time_de, range_de, duration_de) VALUES

-- Tierische Boten
('Tierische Boten', 'Animal Messenger', 2, 'Druid', 'Enchantment', 'Ja', '1 action', 'V, S, M', 'Nein', 'PHB', '212', '212',
'Du verwendest ein winziges Tier, um eine Nachricht zu übermitteln. Wähle ein winziges Tier, das du sehen kannst und das sich im Umkreis befindet. Du gibst ihm eine Nachricht von höchstens fünfundzwanzig Wörtern. Das Tier reist für die Dauer des Zaubers in die von dir angegebene Richtung und legt dabei etwa 80 Kilometer pro 24 Stunden für einen fliegenden Boten oder 40 Kilometer für andere Tiere zurück. Wenn der Bote sein Ziel erreicht, übermittelt er deine Nachricht an die Kreatur, die du beschrieben hast, und ahmt dabei deine Stimme nach. Der Bote spricht nur zu einer Kreatur, die deiner Beschreibung entspricht. Wenn der Bote sein Ziel nicht erreicht, bevor der Zauber endet, geht die Nachricht verloren und das Tier kehrt zu seinem normalen Verhalten zurück. Auf höheren Stufen: Wenn du diesen Zauber mit einem Zauberplatz der 3. Stufe oder höher wirkst, erhöht sich die Dauer des Zaubers um 48 Stunden für jede Stufe über der 2.',
'By means of this spell, you use an animal to deliver a message. Choose a Tiny beast you can see within range. You specify a location, which you must have visited, and a recipient who matches a general description, such as a man or woman dressed in the uniform of the town guard or a red-haired dwarf wearing a pointed hat. You also speak a message of up to twenty-five words. The target beast travels for the duration of the spell toward the specified location, covering about 50 miles per 24 hours for a flying messenger, or 25 miles for other animals. When the messenger arrives, it delivers your message to the creature that you described, replicating the sound of your voice. The messenger speaks only to a creature matching the description you gave. If the messenger does not reach its destination before the spell ends, the message is lost, and the beast makes its way back to where you cast this spell. At Higher Levels: If you cast this spell using a spell slot of 3rd level or higher, the duration of the spell increases by 48 hours for each slot level above 2nd.',
'Verzauberung', '1 Aktion', '9 Meter', '24 Stunden'),

-- Rindenhaut
('Rindenhaut', 'Barkskin', 2, 'Druid', 'Transmutation', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '217', '217',
'Du berührst eine bereitwillige Kreatur. Bis der Zauber endet, wird die Haut des Ziels rau und rindenartig, und die Rüstungsklasse des Ziels kann nicht weniger als 16 betragen, unabhängig davon, welche Rüstung es trägt.',
'You touch a willing creature. Until the spell ends, the target skin has a rough, bark-like appearance, and the target AC cannot be less than 16, regardless of what kind of armor it is wearing.',
'Verwandlung', '1 Aktion', 'Berührung', 'Konzentration, bis zu 1 Stunde'),

-- Fallen finden
('Fallen finden', 'Find Traps', 2, 'Druid', 'Divination', 'Nein', '1 action', 'V, S', 'Nein', 'PHB', '241', '241',
'Du spürst die Anwesenheit von Fallen in Sichtweite und im Umkreis. Eine Falle ist im Sinne dieses Zaubers alles, was einen plötzlichen oder unerwarteten Effekt auslösen würde, den du als schädlich oder unerwünscht betrachtest und der speziell von seinem Schöpfer entwickelt wurde. So würde der Zauber eine Fläche aufdecken, die durch einen Alarm-Zauber betroffen ist, eine Grube oder einen vergifteten Pfeil in einer versteckten Falle. Der Zauber würde aber keine natürliche Schwäche im Boden, eine instabile Decke oder eine versteckte Fallgrube aufdecken. Dieser Zauber offenbart lediglich, dass eine Falle vorhanden ist. Du erfährst nicht den Standort jeder Falle, wohl aber die allgemeine Art der Gefahr, die von einer von dir gespürten Falle ausgeht.',
'You sense the presence of any trap within range that is within line of sight. A trap, for the purpose of this spell, includes anything that would inflict a sudden or unexpected effect you consider harmful or undesirable, which was specifically intended as such by its creator. Thus, the spell would sense an area affected by the alarm spell, a glyph of warding, or a mechanical pit trap, but it would not reveal a natural weakness in the floor, an unstable ceiling, or a hidden sinkhole. This spell merely reveals that a trap is present. You do not learn the location of each trap, but you do learn the general nature of the danger posed by a trap you sense.',
'Erkenntniszauber', '1 Aktion', '36 Meter', 'Unmittelbar'),

-- Flammenkugel
('Flammenkugel', 'Flaming Sphere', 2, 'Druid', 'Conjuration', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '242', '242',
'Eine 1,5 Meter große Kugel aus Feuer erscheint in einem freien Bereich deiner Wahl im Umkreis und besteht für die Dauer des Zaubers. Jede Kreatur, die ihren Zug innerhalb von 1,5 Metern um die Kugel beendet, muss einen Geschicklichkeitsrettungswurf ablegen. Bei einem Misserfolg erleidet die Kreatur 2W6 Feuerschaden, bei Erfolg halb so viel Schaden. Als Bonusaktion kannst du die Kugel bis zu 9 Meter bewegen. Wenn du die Kugel in eine Kreatur rammst, muss diese Kreatur den Rettungswurf gegen den Schaden der Kugel ablegen, und die Kugel stoppt ihre Bewegung in diesem Zug. Wenn du die Kugel bewegst, kannst du sie über Hindernisse von bis zu 1,5 Metern Höhe lenken und über Gruben von bis zu 3 Metern Breite springen lassen. Die Kugel entzündet brennbare Gegenstände, die nicht getragen oder gehalten werden, und spendet helles Licht in einem Radius von 6 Metern und dämmriges Licht für weitere 6 Meter. Auf höheren Stufen: Wenn du diesen Zauber mit einem Zauberplatz der 3. Stufe oder höher wirkst, erhöht sich der Schaden um 1W6 für jede Stufe über der 2.',
'A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration. Any creature that ends its turn within 5 feet of the sphere must make a Dexterity saving throw. The creature takes 2d6 fire damage on a failed save, or half as much damage on a successful one. As a bonus action, you can move the sphere up to 30 feet. If you ram the sphere into a creature, that creature must make the saving throw against the sphere damage, and the sphere stops moving this turn. When you move the sphere, you can direct it over barriers up to 5 feet tall and jump it across pits up to 10 feet wide. The sphere ignites flammable objects not being worn or carried, and it sheds bright light in a 20-foot radius and dim light for an additional 20 feet. At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d6 for each slot level above 2nd.',
'Beschwörung', '1 Aktion', '18 Meter', 'Konzentration, bis zu 1 Minute'),

-- Windböe
('Windböe', 'Gust of Wind', 2, 'Druid', 'Evocation', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '248', '248',
'Eine Linie aus starkem Wind, 18 Meter lang und 3 Meter breit, entsteht von dir ausgehend in eine Richtung deiner Wahl für die Dauer des Zaubers. Jede Kreatur, die ihren Zug in der Linie beginnt, muss einen Stärkerettungswurf bestehen oder wird 4,5 Meter von dir weggeschoben in Richtung der Linie. Jede Kreatur in der Linie muss 30 cm Bewegung für jeden 30 cm aufwenden, den sie sich dir nähert. Der Wind zerstreut Gas oder Dampf und löscht Kerzen, Fackeln und ähnliche ungeschützte Flammen in dem Bereich. Er bringt geschützte Flammen wie Laternen zum Flackern, sodass sie eine 50-prozentige Chance haben, zu erlöschen. Als Bonusaktion in jedem deiner Züge, bevor der Zauber endet, kannst du die Richtung ändern, in die die Linie von dir ausgeht.',
'A line of strong wind 60 feet long and 10 feet wide blasts from you in a direction you choose for the spell duration. Each creature that starts its turn in the line must succeed on a Strength saving throw or be pushed 15 feet away from you in a direction following the line. Any creature in the line must spend 2 feet of movement for every 1 foot it moves when moving closer to you. The gust disperses gas or vapor, and it extinguishes candles, torches, and similar unprotected flames in the area. It causes protected flames, such as those of lanterns, to dance wildly and has a 50 percent chance to extinguish them. As a bonus action on each of your turns before the spell ends, you can change the direction in which the line blasts from you.',
'Hervorrufung', '1 Aktion', 'Selbst (18 Meter Linie)', 'Konzentration, bis zu 1 Minute'),

-- Hitze-Metall
('Hitze-Metall', 'Heat Metal', 2, 'Druid', 'Transmutation', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '250', '250',
'Wähle ein hergestelltes Metallobjekt, wie eine Metallwaffe oder ein Stück schwere oder mittelschwere Metallrüstung, das du im Umkreis sehen kannst. Du lässt das Objekt rot glühen. Jede Kreatur in physischem Kontakt mit dem Objekt erleidet 2W8 Feuerschaden, wenn du den Zauber wirkst. Bis der Zauber endet, kannst du in jedem deiner Züge eine Bonusaktion verwenden, um diesen Schaden erneut zu verursachen. Wenn eine Kreatur das Objekt hält oder trägt und den Schaden erleidet, muss sie einen Konstitutionsrettungswurf bestehen oder lässt das Objekt fallen, wenn sie dazu in der Lage ist. Wenn sie das Objekt nicht fallen lässt, hat sie einen Nachteil bei Angriffswürfen und Attributswürfen bis zum Beginn deines nächsten Zuges. Auf höheren Stufen: Wenn du diesen Zauber mit einem Zauberplatz der 3. Stufe oder höher wirkst, erhöht sich der Schaden um 1W8 für jede Stufe über der 2.',
'Choose a manufactured metal object, such as a metal weapon or a suit of heavy or medium metal armor, that you can see within range. You cause the object to glow red-hot. Any creature in physical contact with the object takes 2d8 fire damage when you cast the spell. Until the spell ends, you can use a bonus action on each of your subsequent turns to cause this damage again. If a creature is holding or wearing the object and takes the damage from it, the creature must succeed on a Constitution saving throw or drop the object if it can. If it does not drop the object, it has disadvantage on attack rolls and ability checks until the start of your next turn. At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.',
'Verwandlung', '1 Aktion', '18 Meter', 'Konzentration, bis zu 1 Minute'),

-- Person festhalten
('Person festhalten', 'Hold Person', 2, 'Druid', 'Enchantment', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '251', '251',
'Wähle einen Humanoiden, den du im Umkreis sehen kannst. Das Ziel muss einen Weisheitsrettungswurf bestehen oder wird für die Dauer des Zaubers gelähmt. Am Ende jedes seiner Züge kann das Ziel einen weiteren Weisheitsrettungswurf ablegen. Bei einem Erfolg endet der Zauber auf das Ziel. Auf höheren Stufen: Wenn du diesen Zauber mit einem Zauberplatz der 3. Stufe oder höher wirkst, kannst du für jede Stufe über der 2. einen zusätzlichen Humanoiden als Ziel wählen. Die Humanoiden dürfen nicht weiter als 9 Meter voneinander entfernt sein, wenn du den Zauber wirkst.',
'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target. At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd. The humanoids must be within 30 feet of each other when you target them.',
'Verzauberung', '1 Aktion', '18 Meter', 'Konzentration, bis zu 1 Minute'),

-- Geringere Wiederherstellung
('Geringere Wiederherstellung', 'Lesser Restoration', 2, 'Druid', 'Abjuration', 'Nein', '1 action', 'V, S', 'Nein', 'PHB', '255', '255',
'Du berührst eine Kreatur und kannst entweder eine Krankheit beenden, die sie betrifft, oder einen Zustand aufheben. Der Zustand kann betäubt, gelähmt, taub, vergiftet oder versteinernd sein.',
'You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.',
'Bannzauber', '1 Aktion', 'Berührung', 'Unmittelbar'),

-- Tiere oder Pflanzen finden
('Tiere oder Pflanzen finden', 'Locate Animals or Plants', 2, 'Druid', 'Divination', 'Ja', '1 action', 'V, S, M', 'Nein', 'PHB', '256', '256',
'Beschreibe oder benenne eine bestimmte Art von Tier oder Pflanze. Durch Konzentration auf die Stimme der Natur in deiner Umgebung erfährst du die Richtung und Entfernung zur nächstgelegenen Kreatur oder Pflanze dieser Art im Umkreis von 8 Kilometern, falls vorhanden.',
'Describe or name a specific kind of beast or plant. Concentrating on the voice of nature in your surroundings, you learn the direction and distance to the closest creature or plant of that kind within 5 miles, if any are present.',
'Erkenntniszauber', '1 Aktion', 'Selbst', 'Unmittelbar'),

-- Objekt finden
('Objekt finden', 'Locate Object', 2, 'Druid', 'Divination', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '256', '256',
'Beschreibe oder benenne ein Objekt, das dir vertraut ist. Du spürst die Richtung zum Standort des Objekts, solange sich dieses Objekt im Umkreis von 300 Metern befindet. Wenn sich das Objekt bewegt, weißt du die Richtung seiner Bewegung. Der Zauber kann ein bestimmtes Objekt lokalisieren, das dir bekannt ist, solange du es mindestens einmal aus der Nähe (innerhalb von 9 Metern) gesehen hast. Alternativ kann der Zauber das nächstgelegene Objekt einer bestimmten Art lokalisieren, wie etwa eine bestimmte Art von Kleidung, Schmuck, Möbel, Werkzeug oder Waffe. Dieser Zauber kann das Objekt nicht finden, wenn eine direkte Verbindung zwischen dir und dem Objekt durch Blei blockiert wird, selbst wenn es nur eine dünne Bleischicht ist.',
'Describe or name an object that is familiar to you. You sense the direction to the object location, as long as that object is within 1,000 feet of you. If the object is in motion, you know the direction of its movement. The spell can locate a specific object known to you, as long as you have seen it up close, within 30 feet, at least once. Alternatively, the spell can locate the nearest object of a particular kind, such as a certain kind of apparel, jewelry, furniture, tool, or weapon. This spell cannot locate an object if any thickness of lead, even a thin sheet, blocks a direct path between you and the object.',
'Erkenntniszauber', '1 Aktion', 'Selbst', 'Konzentration, bis zu 10 Minuten'),

-- Mondstrahl
('Mondstrahl', 'Moonbeam', 2, 'Druid', 'Evocation', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '261', '261',
'Ein silberner Lichtstrahl scheint in einem Zylinder mit einem Radius von 1,5 Metern und einer Höhe von 12 Metern herab, der auf einem Punkt im Umkreis zentriert ist. Bis der Zauber endet, erfüllt dämmriges Licht den Zylinder. Wenn eine Kreatur den Bereich des Zaubers zum ersten Mal in einem Zug betritt oder dort ihren Zug beginnt, wird sie von gespenstischen Flammen umhüllt, die brennende Schmerzen verursachen, und muss einen Konstitutionsrettungswurf ablegen. Bei einem Misserfolg erleidet sie 2W10 gleißenden Schaden, bei Erfolg halb so viel Schaden. Ein Gestaltwandler hat einen Nachteil bei diesem Rettungswurf. Wenn er scheitert, kehrt er sofort in seine ursprüngliche Form zurück und kann für die Dauer des Zaubers keine andere Form annehmen. In jedem deiner Züge nach dem Wirken dieses Zaubers kannst du eine Aktion verwenden, um den Strahl bis zu 18 Meter in jede Richtung zu bewegen. Auf höheren Stufen: Wenn du diesen Zauber mit einem Zauberplatz der 3. Stufe oder höher wirkst, erhöht sich der Schaden um 1W10 für jede Stufe über der 2.',
'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder centered on a point within range. Until the spell ends, dim light fills the cylinder. When a creature enters the spell area for the first time on a turn or starts its turn there, it is engulfed in ghostly flames that cause searing pain, and it must make a Constitution saving throw. It takes 2d10 radiant damage on a failed save, or half as much damage on a successful one. A shapechanger makes its saving throw with disadvantage. If it fails, it also instantly reverts to its original form and cannot assume a different form until it leaves the spell light. On each of your turns after you cast this spell, you can use an action to move the beam up to 60 feet in any direction. At Higher Levels: When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d10 for each slot level above 2nd.',
'Hervorrufung', '1 Aktion', '36 Meter', 'Konzentration, bis zu 1 Minute'),

-- Spurlos gehen
('Spurlos gehen', 'Pass without Trace', 2, 'Druid', 'Abjuration', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '264', '264',
'Ein Schleier aus Schatten und Stille strahlt von dir aus und verbirgt dich und deine Gefährten vor Entdeckung. Für die Dauer des Zaubers erhält jede Kreatur deiner Wahl innerhalb von 9 Metern um dich (einschließlich dir) einen Bonus von +10 auf Geschicklichkeitswürfe (Heimlichkeit) und kann nicht durch Spuren verfolgt werden, es sei denn, die Kreatur entscheidet sich, Spuren zu hinterlassen.',
'A veil of shadows and silence radiates from you, masking you and your companions from detection. For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and cannot be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.',
'Bannzauber', '1 Aktion', 'Selbst', 'Konzentration, bis zu 1 Stunde'),

-- Schutz vor Gift
('Schutz vor Gift', 'Protection from Poison', 2, 'Druid', 'Abjuration', 'Nein', '1 action', 'V, S', 'Nein', 'PHB', '270', '270',
'Du berührst eine Kreatur. Wenn sie vergiftet ist, neutralisierst du das Gift. Wenn mehr als ein Gift die Kreatur betrifft, neutralisierst du ein Gift, von dem du weißt, dass es vorhanden ist, oder du neutralisierst eines nach dem Zufallsprinzip. Für die Dauer des Zaubers hat das Ziel einen Vorteil bei Rettungswürfen gegen Vergiftung und hat Widerstand gegen Giftschaden.',
'You touch a creature. If it is poisoned, you neutralize the poison. If more than one poison afflicts the target, you neutralize one poison that you know is present, or you neutralize one at random. For the duration, the target has advantage on saving throws against being poisoned, and it has resistance to poison damage.',
'Bannzauber', '1 Aktion', 'Berührung', '1 Stunde'),

-- Dornenwuchs
('Dornenwuchs', 'Spike Growth', 2, 'Druid', 'Transmutation', 'Nein', '1 action', 'V, S, M', 'Ja', 'PHB', '277', '277',
'Der Boden in einem Radius von 6 Metern, der auf einem Punkt im Umkreis zentriert ist, verwandelt sich in schwieriges Gelände für die Dauer des Zaubers. Wenn eine Kreatur den Bereich betritt oder sich darin bewegt, erleidet sie 2W4 Stichschaden für jeden 1,5 Meter, den sie sich bewegt. Die Verwandlung des Bodens ist getarnt, sodass er natürlich aussieht. Jede Kreatur, die den Bereich nicht sehen kann, wenn der Zauber gewirkt wird, muss einen Weisheitswurf (Wahrnehmung) gegen deinen Zauber-SG ablegen, um zu erkennen, dass das Gelände gefährlich ist, bevor sie den Bereich betritt.',
'The ground in a 20-foot radius centered on a point within range twists and sprouts hard spikes and thorns. The area becomes difficult terrain for the duration. When a creature moves into or within the area, it takes 2d4 piercing damage for every 5 feet it travels. The transformation of the ground is camouflaged to look natural. Any creature that cannot see the area at the time the spell is cast must make a Wisdom (Perception) check against your spell save DC to recognize the terrain as hazardous before entering it.',
'Verwandlung', '1 Aktion', '45 Meter', 'Konzentration, bis zu 10 Minuten');
