-- Teil 3: Level 4-9 Zauber (FINALE)
-- Führe dies nach Teil 1 und 2 aus

-- ============================================
-- LEVEL 4 ZAUBER - 21 Zauber
-- ============================================

UPDATE `spells` SET `description_de` = 'Du berührst eine Kreatur. Für die Dauer werden die Bewegungen der Kreatur nicht durch schwieriges Gelände eingeschränkt, und Zauber und andere magische Effekte können weder ihre Bewegungsrate reduzieren noch sie gelähmt oder festgehalten machen. Die Kreatur kann auch 1,5 m Bewegung aufwenden, um automatisch aus nicht-magischen Fesseln zu entkommen. Zusätzlich kann sich die Kreatur unter Wasser bewegen und atmen.', `range_de` = 'Berührung', `duration_de` = '1 Stunde', `school_de` = 'Bannzauber' WHERE `id` = 82;

UPDATE `spells` SET `description_de` = 'Nekromantische Energie strömt aus dir und entwässert Feuchtigkeit und Vitalität aus einer Kreatur, die du sehen kannst. Das Ziel muss einen Konstitutionsrettungswurf bestehen oder **8W8 nekrotischen Schaden** erleiden, oder halb so viel bei Erfolg. Dieser Zauber hat keine Wirkung auf Untote oder Konstrukte. Falls du eine Pflanze oder einen Pflanzenkre

atur als Ziel wählst, macht sie den Rettungswurf mit Nachteil, und der Zauber verursacht maximalen Schaden gegen sie. Falls du eine nicht-magische Pflanze als Ziel wählst, die keine Kreatur ist, muss sie keinen Rettungswurf machen; sie verwelkt einfach und stirbt. **Auf höheren Stufen:** +1W8 Schaden pro Zaubergrad über 4.', `range_de` = '9 m', `duration_de` = 'Unmittelbar', `school_de` = 'Nekromantie' WHERE `id` = 83;

UPDATE `spells` SET `description_de` = 'Hagelkörner von Eis und Steinen regnen in einem 6-m-Radius-Zylinder mit 12 m Höhe, zentriert auf einem Punkt innerhalb der Reichweite. Jede Kreatur im Zylinder muss einen Geschicklichkeitsrettungswurf bestehen oder **2W8 Wuchtschaden + 4W6 Kälteschaden** erleiden, oder halb so viel bei Erfolg. Hagel verwandelt den Bereich in schwieriges Gelände, bis zum Ende deines nächsten Zuges. **Auf höheren Stufen:** +1W8 Wuchtschaden pro Zaubergrad über 4.', `range_de` = '90 m', `duration_de` = 'Unmittelbar', `school_de` = 'Hervorrufung' WHERE `id` = 84;

UPDATE `spells` SET `description_de` = 'Du rufst einen Elementargeist herbei. Er erscheint in einem freien Raum, den du in Reichweite sehen kannst. Dieser körperliche Geist hält für die Dauer an. Wenn du den Zauber wirkst, wählst du ein Element: Luft, Erde, Feuer oder Wasser. Die Kreatur ähnelt einem zweibeinigen Elementar-Wesen aus dem gewählten Element. Die Kreatur verschwindet, wenn ihre TP auf 0 sinken oder der Zauber endet. Die Kreatur ist freundlich dir und deinen Gefährten gegenüber. **Auf höheren Stufen:** +2 Stufen erhöhen alle Schadenswürfel um 1.', `range_de` = '27 m', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Beschwörung' WHERE `id` = 85;

UPDATE `spells` SET `description_de` = 'Wähle eine Kreatur, die du in Reichweite sehen kannst. Das Ziel muss einen Weisheitsrettungswurf bestehen oder für die Dauer anfällig gegenüber einer Schadensart werden, die du wählst: Säure, Kälte, Feuer, Blitz oder Schall. Außerdem, wenn das Ziel von einem Angriff oder Zauber getroffen wird, der Schaden des gewählten Typs verursacht, erleidet es **zusätzlich 2W6 Schaden dieses Typs**. Dann endet der Zauber. **Auf höheren Stufen:** Du kannst eine zusätzliche Kreatur pro Zaubergrad über 4 als Ziel wählen.', `range_de` = '27 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Verwandlung' WHERE `id` = 86;

UPDATE `spells` SET `description_de` = 'Du erschaffst eine Feuerwand auf einer festen Oberfläche innerhalb der Reichweite. Du kannst die Wand bis zu 18 m lang, 6 m hoch und 30 cm dick machen, oder eine ringartige Wand mit bis zu 6 m Durchmesser, 6 m Höhe und 30 cm Dicke. Die Wand ist undurchsichtig und hält für die Dauer. Wenn die Wand erscheint, muss jede Kreatur in ihrem Bereich einen Geschicklichkeitsrettungswurf bestehen oder **5W8 Feuerschaden** erleiden, oder halb so viel bei Erfolg. Eine Seite der Wand (von dir gewählt) verursacht **5W8 Feuerschaden** an Kreaturen, die ihren Zug innerhalb von 3 m von dieser Seite beenden. **Auf höheren Stufen:** +1W8 Schaden pro Zaubergrad über 4.', `range_de` = '36 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Hervorrufung' WHERE `id` = 87;

UPDATE `spells` SET `description_de` = 'Die Kraft der Natur durchdringt dich und verleiht dir einen bestialischen oder baumartigen Aspekt (du wählst). Bis der Zauber endet, erhältst du einen der folgenden Effekte: **Uralter Baum:** +10 TP, Vorteil auf Konstitutionsrettungswürfe, Resistenz gegen Wucht/Stich/Hieb-Schaden. **Großer Bär:** +10 TP, Vorteil auf Stärkewürfe, zusätzlich 1W6 Kraftschaden bei Nahkampfangriffen.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Verwandlung' WHERE `id` = 88;

UPDATE `spells` SET `description_de` = 'Beschreibe oder benenne eine Kreatur, die dir vertraut ist. Du spürst die Richtung zum Standort der Kreatur, solange sie sich innerhalb von 300 m von dir befindet. Falls die Kreatur sich bewegt, kennst du die Richtung ihrer Bewegung. Der Zauber kann eine spezifische Kreatur lokalisieren, die du kennst, oder die nächste Kreatur einer bestimmten Art. Der Zauber kann die Kreatur nicht finden, falls fließendes Wasser mindestens 3 m breit zwischen dir und der Kreatur ist.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Erkenntniszauber' WHERE `id` = 89;

UPDATE `spells` SET `description_de` = 'Du versuchst, eine Kreatur zu bezaubern, die du in Reichweite sehen kannst. Sie muss einen Weisheitsrettungswurf bestehen, und sie macht dies mit Vorteil, falls du oder deine Gefährten sie bekämpfen. Falls sie den Rettungswurf nicht besteht, ist sie von dir bezaubert, bis der Zauber endet oder bis du oder deine Gefährten ihr etwas Schädliches antun. **Auf höheren Stufen:** Du kannst eine zusätzliche Kreatur pro Zaubergrad über 4 als Ziel wählen.', `range_de` = '9 m', `duration_de` = '1 Stunde', `school_de` = 'Verzauberung' WHERE `id` = 90;

UPDATE `spells` SET `description_de` = 'Du verwandelst bis zu zehn Käfer, Spinnen, Tausendfüßer oder Skorpione in riesige Versionen ihrer natürlichen Form für die Dauer. Ein Käfer wird zu einem Riesenkäfer, eine Spinne zu einer Riesenspinne, ein Tausendfüßer zu einem Riesentausendfüßer und ein Skorpion zu einem Riesenskorpion. Jede Kreatur befolgt deine verbalen Befehle, und im Kampf handeln sie in jedem deiner Züge. Der SL hat die Statistiken für diese Kreaturen. **Auf höheren Stufen:** +4 Insekten pro Zaubergrad über 4.', `range_de` = '9 m', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Verwandlung' WHERE `id` = 91;

UPDATE `spells` SET `description_de` = 'Du machst natürliches Gelände in einem 45-m-Würfel innerhalb der Reichweite wie ein anderes natürliches Gelände aussehen, klingen und riechen. Offenes Feld könnte wie ein Sumpf aussehen, ein Weg könnte wie ein Abhang aussehen, oder eine Felsspalte könnte wie eine breite Straße aussehen. Die Illusion umfasst keine sichtbaren Kreaturen. Die Illusion hält für die Dauer an. Physischer Kontakt mit dem Gelände offenbart es als Illusion.', `range_de` = '90 m', `duration_de` = '24 Stunden', `school_de` = 'Illusion' WHERE `id` = 92;

UPDATE `spells` SET `description_de` = 'Du beschwörst eine Ranke, die am Boden aus einem Punkt in Reichweite sprießt, den du sehen kannst. Wenn du diesen Zauber wirkst, kannst du die Ranke anweisen, eine Kreatur innerhalb von 9 m Entfernung zu greifen. Die Kreatur muss einen Geschicklichkeitsrettungswurf bestehen oder wird bis zum Ende des Zaubers festgehalten. Du kannst die Ranke als Bonusaktion anweisen, sich bis zu 9 m zu einem anderen Punkt auf dem Boden zu bewegen und eine andere Kreatur zu greifen. Eine festgehaltene Kreatur kann ihren Zug damit verbringen, einen Stärkerettungswurf zu machen, um sich zu befreien.', `range_de` = '9 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Beschwörung' WHERE `id` = 93;

UPDATE `spells` SET `description_de` = 'Du beschwörst Elementare, die in freien Räumen erscheinen, die du in Reichweite sehen kannst. Wähle eine Option: **Acht Elementare mit HG 1/4, vier mit HG 1/2, oder zwei mit HG 1**. Die Elementare verschwinden, wenn sie auf 0 TP fallen oder der Zauber endet. Die beschworenen Kreaturen sind freundlich dir und deinen Gefährten gegenüber. **Auf höheren Stufen:** Doppelte Anzahl pro 2 Zaubergrade über 4.', `range_de` = '27 m', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Beschwörung' WHERE `id` = 94;

UPDATE `spells` SET `description_de` = 'Du berührst einen Steingegenstand von mittlerer Größe oder kleiner oder einen Abschnitt von Stein, der nicht mehr als 1,5 m in jede Dimension misst, und formst ihn in jede Form, die deinen Zwecken dient. Du könntest z.B. einen großen Felsen in eine Waffe, ein Idol oder eine Truhe formen oder eine kleine Passage durch eine Mauer machen, solange die Wand weniger als 1,5 m dick ist. Du könntest auch eine Steintür formen oder ihren Rahmen, um die Tür zu versiegeln. Das von dir erschaffene Objekt kann höchstens zwei Scharniere und eine Verriegelung haben, aber feinere mechanische Details sind nicht möglich.', `range_de` = 'Berührung', `duration_de` = 'Unmittelbar', `school_de` = 'Verwandlung' WHERE `id` = 95;

UPDATE `spells` SET `description_de` = 'Dieser Zauber verwandelt das Fleisch einer willigen Kreatur, die du berührst, so hart wie Stein. Bis der Zauber endet, hat das Ziel Resistenz gegen nicht-magischen Wucht-, Stich- und Hiebschaden.', `range_de` = 'Berührung', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Bannzauber' WHERE `id` = 96;

UPDATE `spells` SET `description_de` = 'Du versuchst, eine Bestie zu befehligen, die du in Reichweite sehen kannst. Sie muss einen Weisheitsrettungswurf bestehen, oder sie wird von dir für die Dauer bezaubert. Falls du oder deine Gefährten die Bestie bekämpfen, hat sie Vorteil auf den Rettungswurf. Während die Bestie bezaubert ist, hast du eine telepathische Verbindung mit ihr, solange ihr euch auf derselben Existenzebene befindet. Du kannst diese Verbindung nutzen, um der Bestie Befehle zu geben (keine Aktion erforderlich). **Auf höheren Stufen:** +1 Stufe erhöht die Dauer (5 = 10 Min, 6 = 1 Std, 7 = 8 Std).', `range_de` = '18 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Verzauberung' WHERE `id` = 97;

UPDATE `spells` SET `description_de` = 'Dieser Zauber verwandelt eine Kreatur, die du sehen kannst, in eine neue Form. Eine unwillige Kreatur muss einen Weisheitsrettungswurf bestehen, um den Effekt zu vermeiden. Der Zauber hat keine Wirkung auf Gestaltwandler oder Kreaturen mit 0 TP. Die neue Form kann jedes Tier sein mit einem HG gleich oder kleiner als der HG des Ziels (oder der Stufe des Ziels). Die Zielkreatur erhält die Spielwerte der gewählten Tierform, behält aber ihre Gesinnung und Persönlichkeit. Die Kreatur kann keine Zauber wirken. **Auf höheren Stufen:** +1 Stufe erhöht maximalen HG um 1.', `range_de` = '18 m', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Verwandlung' WHERE `id` = 98;

UPDATE `spells` SET `description_de` = 'Dieser Zauber greift und verdreht die Gedanken von Kreaturen und erzeugt Illusionen und verursacht unkontrollierte Aktionen. Jede Kreatur in einer 3-m-Radius-Sphäre, zentriert auf einem Punkt deiner Wahl, muss einen Weisheitsrettungswurf bestehen, wenn du diesen Zauber wirkst, oder sie wird betroffen. Eine betroffene Kreatur kann nicht Reaktionen ausführen und muss zu Beginn jedes ihrer Züge einen W10 würfeln, um ihr Verhalten für diesen Zug zu bestimmen. **Auf höheren Stufen:** +1,5 m Radius pro Zaubergrad über 4.', `range_de` = '27 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Verzauberung' WHERE `id` = 99;

UPDATE `spells` SET `description_de` = 'Bis der Zauber endet, kontrollierst du jedes frei stehendes Wasser in einem Bereich, den du wählst, der ein Würfel von bis zu 30 m Kantenlänge ist. Du kannst einen der folgenden Effekte wählen: **Flutwelle** (Kreaturen in der Welle: GES-RW oder 2W8 Wuchtschaden); **Teil Wasser** (Furche durch Wasser bis zu 30 m lang); **Wirbel** (5W8 Wuchtschaden für Kreaturen im Wasser); **Umleiten** (Wasser fließt in eine andere Richtung).', `range_de` = '90 m', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Verwandlung' WHERE `id` = 100;

UPDATE `spells` SET `description_de` = 'Du beschwörst eine Sphäre aus Wasser mit einem Radius von 1,5 m an einem Punkt in Reichweite, den du sehen kannst. Die Sphäre kann in der Luft schweben, aber nicht höher als 3 m über dem Boden. Die Sphäre hält für die Dauer an. Jede Kreatur in der Sphäre, wenn du sie erschaffst, oder die ihren Zug innerhalb von 1,5 m davon beendet, muss einen Stärkerettungswurf bestehen oder wird von der Sphäre verschluckt und festgehalten. Eine verschluckte Kreatur kann versuchen, sich zu befreien (Stärke-Wurf als Aktion). Du kannst die Sphäre als Bonusaktion bis zu 9 m bewegen. **Auf höheren Stufen:** +1,5 m Radius pro Zaubergrad über 4.', `range_de` = '27 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Beschwörung' WHERE `id` = 101;

UPDATE `spells` SET `description_de` = 'Du beschwörst Feenwesen, die in freien Räumen erscheinen, die du in Reichweite sehen kannst. Wähle eine Option: **Ein Feenwesen mit HG 2, zwei mit HG 1, vier mit HG 1/2, oder acht mit HG 1/4**. Die beschworenen Kreaturen verschwinden, wenn sie auf 0 TP fallen oder der Zauber endet. Die Kreaturen sind freundlich dir und deinen Gefährten gegenüber. **Auf höheren Stufen:** Doppelte Anzahl pro 2 Zaubergrade über 4.', `range_de` = '18 m', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Beschwörung' WHERE `id` = 102;

-- ============================================
-- LEVEL 5 ZAUBER - 17 Zauber
-- ============================================

UPDATE `spells` SET `description_de` = 'Deine Berührung infundiert Krankheit. Mache einen Nahkampf-Zauberangriff gegen eine Kreatur in Reichweite. Bei einem Treffer erleidet das Ziel **11W8 Giftschaden**, und es muss einen Konstitutionsrettungswurf bestehen oder wird vergiftet. Am Ende jedes seiner Züge kann das vergiftete Ziel den Rettungswurf wiederholen. Bei drei Erfolgen endet der Zauber. Bei drei Misserfolgen wird das Ziel für 7 Tage von einer Krankheit (SL wählt) heimgesucht.', `range_de` = 'Berührung', `duration_de` = '7 Tage', `school_de` = 'Nekromantie' WHERE `id` = 103;

UPDATE `spells` SET `description_de` = 'Du kannst eine Kreatur sehen und hören, die du wählst, auf derselben Existenzebene wie du. Das Ziel muss einen Weisheitsrettungswurf bestehen, der durch dein Wissen über das Ziel modifiziert wird. Bei einem fehlgeschlagenen Rettungswurf erschafft der Zauber einen unsichtbaren Sensor innerhalb von 3 m vom Ziel. Du kannst durch den Sensor sehen und hören, als wärst du dort. Der Sensor bewegt sich mit dem Ziel. Eine Kreatur, die den unsichtbaren Sensor sehen kann, sieht eine leuchtende Kugel von der Größe deiner Faust.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Erkenntniszauber' WHERE `id` = 104;

UPDATE `spells` SET `description_de` = 'Du bindest einen Elementar, Feenwesen oder Teufel zum Dienst. Die Kreatur muss innerhalb der Reichweite für die gesamte Wirkzeit des Zaubers sein. Am Ende des Wirkens muss die Kreatur einen Charismarettungswurf bestehen oder an dich gebunden werden für die Dauer. Falls die Kreatur von dir oder deinen Gefährten beschworen wurde, hat sie Nachteil auf diesen Rettungswurf. Eine gebundene Kreatur muss deinen Anweisungen so gut wie möglich folgen. **Auf höheren Stufen:** Dauer erhöht sich (6 = 10 Tage, 7 = 30 Tage, 8 = 180 Tage, 9 = 1 Jahr).', `range_de` = '18 m', `duration_de` = '24 Stunden', `school_de` = 'Bannzauber' WHERE `id` = 105;

UPDATE `spells` SET `description_de` = 'Du verschmilzt kurz mit der Natur und erlangst Wissen über das umgebende Gelände. Im Freien gewährt dir der Zauber Wissen über das Land innerhalb von 5 km von dir. In Höhlen und anderen natürlichen unterirdischen Umgebungen sinkt der Radius auf 90 m. Der Zauber funktioniert nicht dort, wo die Natur durch Konstruktion ersetzt wurde (Städte, Dungeons). Du erlangst sofort Wissen über bis zu drei Fakten deiner Wahl über Gelände, Pflanzen, Mineralien, Gewässer, Volk, mächtige Himmlische/Feenwesen/Teufel/Untote, oder allgemeiner Einfluss anderer Ebenen.', `range_de` = 'Selbst', `duration_de` = 'Unmittelbar', `school_de` = 'Erkenntniszauber' WHERE `id` = 106;

UPDATE `spells` SET `description_de` = 'Du rufst einen elementaren Diener herbei. Wähle einen Bereich aus Luft, Erde, Feuer oder Wasser, der einen Würfel von 3 m Kantenlänge füllt, innerhalb der Reichweite. Ein Elementar mit HG 5 oder niedriger, der dem gewählten Bereich entspricht, erscheint in einem freien Raum innerhalb von 3 m davon. Der Elementar verschwindet, wenn er auf 0 TP fällt oder der Zauber endet. Der Elementar ist freundlich dir und deinen Gefährten gegenüber. Würfle Initiative für den Elementar. Er befolgt verbale Befehle. Falls du ihm keinen Befehl gibst, verteidigt er sich, unternimmt aber sonst keine Aktionen. **Auf höheren Stufen:** HG erhöht sich um 1 pro Zaubergrad über 5.', `range_de` = '27 m', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Beschwörung' WHERE `id` = 107;

UPDATE `spells` SET `description_de` = 'Nach Verbringen von 8 Stunden während der Wirkzeit berührst du eine Riesenpflanze oder ein Tier mit Intelligenz 3 oder weniger. Das Ziel muss entweder keinen Intelligenzwert haben oder eine Intelligenz von 3 oder weniger. Das Ziel erhält eine Intelligenz von 10 und die Fähigkeit, eine Sprache zu sprechen, die du kennst. Falls das Ziel eine Pflanze ist, erhält es die Fähigkeit, seine Zweige, Wurzeln, Ranken usw. zu bewegen. Der SL wählt Statistiken für die erwachte Kreatur. Die erwachte Kreatur ist dir und deinen Gefährten gegenüber bezaubert für 30 Tage oder bis du oder deine Gefährten ihr Schaden zufügen.', `range_de` = 'Berührung', `duration_de` = 'Unmittelbar', `school_de` = 'Verwandlung' WHERE `id` = 108;

UPDATE `spells` SET `description_de` = 'Du platzierst einen magischen Befehl auf einer Kreatur, die du in Reichweite sehen kannst, und zwingst sie, dir einen Dienst zu erweisen oder von einer Handlungsweise abzusehen. Falls die Kreatur dich verstehen kann, muss sie einen Weisheitsrettungswurf bestehen oder für die Dauer bezaubert werden. Während die Kreatur von dir bezaubert ist, erleidet sie **5W10 psychischen Schaden** jedes Mal, wenn sie auf eine Weise handelt, die direkt gegen deine Anweisungen verstößt. Eine Aufgabe, die wahrscheinlich zum Tod führt, beendet den Zauber automatisch. **Auf höheren Stufen:** 7-8 = 1 Jahr, 9 = bis aufgehoben.', `range_de` = '18 m', `duration_de` = '30 Tage', `school_de` = 'Verzauberung' WHERE `id` = 109;

UPDATE `spells` SET `description_de` = 'Du trittst einmal an einen lebenden Baum, der Groß oder größer ist, und erscheinst aus einem zweiten lebenden Baum derselben Art innerhalb von 800 km, den du gesehen oder berührt hast, an einem Ort deiner Wahl innerhalb von 1,5 m. Beide Bäume müssen lebendig und mindestens von derselben Größe wie du sein. Du musst den Zielort kennen - nur allgemeine Vorstellungen wie "ein Druiden-Kreis in einem nahen Wald" funktionieren nicht. Deine Bewegung ist die Entfernung zwischen den beiden Bäumen. Falls du keine Bewegung mehr hast, erscheinst du innerhalb von 1,5 m vom Baum, den du betreten hast. Du kannst einen willigen Gefährten von Größe Mittel oder kleiner mitnehmen.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Beschwörung' WHERE `id` = 110;

UPDATE `spells` SET `description_de` = 'Schwärmende, beißende Heuschrecken erfüllen eine Sphäre mit einem Radius von 6 m, zentriert auf einem Punkt deiner Wahl innerhalb der Reichweite. Die Sphäre breitet sich um Ecken herum aus. Die Sphäre bleibt für die Dauer bestehen, und ihr Bereich ist leicht verschleiert. Der Bereich der Sphäre ist schwieriges Gelände. Wenn der Bereich zum ersten Mal in einem Zug erscheint und eine Kreatur darin beginnt, muss diese Kreatur einen Konstitutionsrettungswurf bestehen oder **4W10 Stichschaden** erleiden, oder halb so viel bei Erfolg. Kreaturen sind auch betroffen, wenn sie zum ersten Mal in einem Zug den Bereich betreten. **Auf höheren Stufen:** +1W10 Schaden pro Zaubergrad über 5.', `range_de` = '90 m', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Beschwörung' WHERE `id` = 111;

UPDATE `spells` SET `description_de` = 'Ein Strudel aus Wasser erscheint in einem Punkt, den du in Reichweite sehen kannst. Der Strudel ist ein Zylinder mit 18 m Radius und 30 m Höhe, zentriert auf diesem Punkt. Bis der Zauber endet, ist der Bereich schwieriges Gelände, und jede Kreatur im Bereich am Anfang ihres Zuges oder die zum ersten Mal in einem Zug den Bereich betritt, muss einen Stärkerettungswurf bestehen. Bei einem Misserfolg erleidet sie **6W6 Wuchtschaden** und wird 3 m auf das Zentrum zu gezogen. **Auf höheren Stufen:** +1W6 Schaden pro Zaubergrad über 5.', `range_de` = '36 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Hervorrufung' WHERE `id` = 112;

UPDATE `spells` SET `description_de` = 'Eine Welle heilender Energie strömt aus einem Punkt deiner Wahl innerhalb der Reichweite. Wähle bis zu sechs Kreaturen in einer Sphäre mit 9 m Radius, zentriert auf diesem Punkt. Jedes Ziel erhält **3W8 + dein Zauberwirken-Attributmodifikator** Trefferpunkte zurück. Dieser Zauber hat keine Wirkung auf Untote oder Konstrukte. **Auf höheren Stufen:** +1W8 Heilung pro Zaubergrad über 5.', `range_de` = '18 m', `duration_de` = 'Unmittelbar', `school_de` = 'Hervorrufung' WHERE `id` = 113;

UPDATE `spells` SET `description_de` = 'Eine schimmernde Barriere erstreckt sich von dir aus zu einem Radius von 3 m und bewegt sich mit dir, zentriert auf dir, und hält für die Dauer an. Die Barriere hindert eine betroffene Kreatur daran, durch sie hindurchzugehen oder zu greifen. Eine betroffene Kreatur ist eine, die nicht untot ist und nicht ein Konstrukt ist. Die Barriere verhindert auch, dass eine betroffene Kreatur dich mit magischen Effekten bezaubert, verängstigt oder besitzt. Wenn du dich so bewegst, dass eine betroffene Kreatur gezwungen ist, die Barriere zu durchqueren, endet der Zauber.',  `range_de` = 'Selbst (Radius 3 m)', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Bannzauber' WHERE `id` = 114;

UPDATE `spells` SET `description_de` = 'Eine nicht-magische Steinwand springt aus dem Boden an einem Punkt, den du innerhalb der Reichweite wählst. Die Wand ist 15 cm dick und besteht aus zehn 3x3 m großen Panelen. Jedes Panel muss an ein anderes Panel angrenzen. Alternativ kannst du 3x6 m große Paniele erschaffen, die nur 7,5 cm dick sind. Falls die Wand durch den Raum einer Kreatur schneidet, wird diese Kreatur auf eine Seite der Wand gedrängt (deine Wahl). Falls eine Kreatur von allen Seiten von der Wand umschlossen wäre, kann diese Kreatur einen Geschicklichkeitsrettungswurf machen. Bei Erfolg kann sie ihre Reaktion einsetzen, um sich bis zu ihrer Bewegungsrate zu bewegen, sodass sie nicht länger von der Wand umschlossen ist. Die Wand kann als Deckung dienen. Jedes Panel hat RK 15, 30 TP pro 2,5 cm Dicke. **Auf höheren Stufen:** +10 Panele (3x3m) oder +20 Panele (3x6m) pro Zaubergrad über 5.', `range_de` = '36 m', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Hervorrufung' WHERE `id` = 115;

UPDATE `spells` SET `description_de` = 'Du wählst einen Bereich aus Stein oder Schlamm, den du sehen kannst und der in einen Würfel von 12 m Kantenlänge passt, innerhalb der Reichweite, und wählst einen der folgenden Effekte: **Stein zu Schlamm:** Nicht-magischer Stein wird zu dickem, zähem Schlamm. Jede Kreatur im Schlamm, wenn er erscheint, muss einen Geschicklichkeitsrettungswurf bestehen oder sinkt ein und wird festgehalten. Eine festgehaltene Kreatur kann als Aktion versuchen, sich zu befreien (Stärke- oder Geschicklichkeitswurf). **Schlamm zu Stein:** Nicht-magischer Schlamm oder Treibsand wird zu weichem Stein. Kreaturen, die im Schlamm festgehalten sind, bleiben im Stein eingeschlossen. Eine eingeschlossene Kreatur kann sich befreien, indem sie einen Stärkewurf gegen deinen Zauberrettungswurf-SG macht. Bei Erfolg bricht die Kreatur aus dem Stein. Alternativ kann die Kreatur versuchen, sich aus dem Stein zu graben (Stärke-Wurf).', `range_de` = '36 m', `duration_de` = 'Unmittelbar', `school_de` = 'Verwandlung' WHERE `id` = 116;

UPDATE `spells` SET `description_de` = 'Du berührst eine Kreatur und kannst einen Effekt beenden, der auf sie wirkt. Du kannst eine Erschöpfungsstufe reduzieren oder einen der folgenden Effekte auf das Ziel beenden: einen Effekt, der das Ziel bezaubert oder versteinert; einen Fluch, einschließlich die Einstimmung auf einen verfluchten magischen Gegenstand; jede Reduktion eines der Attributswerte des Ziels; einen Effekt, der einen der maximalen Trefferpunkte des Ziels reduziert.', `range_de` = 'Berührung', `duration_de` = 'Unmittelbar', `school_de` = 'Bannzauber' WHERE `id` = 117;

UPDATE `spells` SET `description_de` = 'Du berührst eine tote humanoide Kreatur, die nicht länger als 10 Tage tot ist. Falls die Seele der Kreatur sowohl frei als auch willig ist, wird die Kreatur mit einem neuen Körper wiederbelebt. Der SL würfelt einen W100 und konsultiert eine Tabelle, um zu bestimmen, welche Form die Kreatur annimmt. Die reinkarnierte Kreatur erinnert sich an ihr früheres Leben und ihre Erfahrungen. Sie behält die Fähigkeiten, die sie in ihrer früheren Form hatte, außer dass sie ihre ursprüngliche Rasse gegen die neue austauscht.', `range_de` = 'Berührung', `duration_de` = 'Unmittelbar', `school_de` = 'Verwandlung' WHERE `id` = 118;

UPDATE `spells` SET `description_de` = 'Du nutzt deinen Willen, um Wind zu erschaffen und zu kontrollieren um dich herum. Wähle einen der folgenden Effekte, wenn du den Zauber wirkst. Der Effekt hält für die Dauer des Zaubers an, oder bis du deine Aktion benutzt, um zu einem anderen Effekt zu wechseln: **Starker Wind:** 30 km/h Wind weht von dir weg in eine 18 m Linie (schwieriges Gelände, Fernkampfangriffe haben Nachteil). **Herabstoß:** Wind strömt von dir abwärts in einem Radius von 3 m. Jede Kreatur am Anfang ihres Zuges muss Stärke-RW bestehen oder 4,5 m zu Boden gedrückt werden. **Aufwind:** Wind strömt von dir aufwärts in 3 m Radius. Du und bis zu 3 Kreaturen erhalten 3 m Fluggeschwindigkeit.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Verwandlung' WHERE `id` = 119;

UPDATE `spells` SET `description_de` = 'Du rufst die Kräfte der Natur herbei, um einen Widersacher zu peinigen. Wähle einen Punkt, den du in Reichweite sehen kannst. Bäume, Wurzeln und Ranken sprießen in einem Würfel von 18 m Kantenlänge, zentriert auf diesem Punkt. Für die Dauer ist dieser Bereich schwieriges Gelände. Wenn eine Kreatur ihren Zug im Bereich beginnt oder zum ersten Mal in einem Zug den Bereich betritt, muss sie einen Geschicklichkeitsrettungswurf bestehen oder **6W8 Hiebschaden** von den peitschenden Ästen und Ranken erleiden. Außerdem muss sie einen Stärkerettungswurf bestehen oder wird für die Dauer festgehalten. Eine festgehaltene Kreatur kann als Aktion versuchen, sich zu befreien (Stärke- oder Geschicklichkeitswurf).', `range_de` = '45 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Hervorrufung' WHERE `id` = 120;

-- ============================================
-- LEVEL 6 ZAUBER - 16 Zauber
-- ============================================

UPDATE `spells` SET `description_de` = 'Du erschaffst eine Wand aus zähen, flexiblen, verflochtenen Dornenbüschen. Die Wand erscheint innerhalb der Reichweite auf einer festen Oberfläche und hält für die Dauer an. Du wählst, die Wand bis zu 18 m lang, 3 m hoch und 1,5 m dick zu machen, oder einen Kreis mit einem Durchmesser von bis zu 6 m, 6 m hoch und 1,5 m dick zu bilden. Die Wand blockiert die Sichtlinie. Wenn die Wand im Raum einer Kreatur erscheint, wird die Kreatur auf eine Seite der Wand gedrängt (deine Wahl), und sie muss einen Geschicklichkeitsrettungswurf bestehen oder **7W8 Stichschaden** erleiden, oder halb so viel bei Erfolg. Eine Kreatur kann sich durch die Wand bewegen, aber langsam und schmerzhaft. Für jeden 30 cm, die sich eine Kreatur durch die Wand bewegt, muss sie 12 m Bewegung aufwenden. Außerdem muss die Kreatur einen Geschicklichkeitsrettungswurf bestehen oder **7W8 Hiebschaden** erleiden, oder halb so viel bei Erfolg. **Auf höheren Stufen:** +1W8 beider Schadensarten pro Zaubergrad über 6.', `range_de` = '36 m', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Beschwörung' WHERE `id` = 121;

UPDATE `spells` SET `description_de` = 'Du rufst die Geister der Natur herbei, um ein Waldgebiet auf Land oder unter Wasser zu beschützen. Das Gebiet kann ein Quadrat von bis zu 90 m Seitenlänge sein. Strukturen, die sich bereits im Gebiet befinden, werden nicht berührt. Du kannst bis zu drei der folgenden magischen Effekte im Gebiet erschaffen: Feste Nebelbänke, Illusionen verstecken Eindringlinge, Dornenranken greifen Eindringlinge an (4W8 Stichschaden bei Eintritt), Feenfeuer auf alle Eindringlinge, Glocken/Hornstoß als Alarm. Der Zauber hält 1 Jahr lang an, außer du benutzt eine Aktion, um ihn früher zu beenden. Die Kreation des Zaubers ist permanent und unabhängig vom Zauber selbst.', `range_de` = '300 m', `duration_de` = '1 Jahr bis aufgehoben', `school_de` = 'Bannzauber' WHERE `id` = 122;

UPDATE `spells` SET `description_de` = 'Du wählst einen Bereich aus Gelände, der nicht größer ist als ein Würfel von 12 m Kantenlänge, innerhalb der Reichweite. Du kannst Erde, Sand oder Lehm im Bereich in jede Weise formen, die deinen Zwecken dient, für die Dauer. Du kannst Erhebungen erhöhen oder senken, Gräben erschaffen oder füllen, oder Säulen bilden. Das Ausmaß dieser Veränderungen darf nicht die Hälfte der größten Dimension des Bereichs überschreiten. Die Veränderungen nehmen 10 Minuten in Anspruch. Am Ende jeder 10 Minuten, in denen du dich auf diesen Zauber konzentrierst, kannst du einen neuen Bereich aus Gelände wählen, um ihn zu beeinflussen. Da die Veränderungen des Geländes langsam erfolgen, werden Kreaturen im Bereich normalerweise nicht gefangen oder verletzt durch die Veränderungen.', `range_de` = '36 m', `duration_de` = 'Konzentration, bis zu 2 Stunden', `school_de` = 'Verwandlung' WHERE `id` = 123;

UPDATE `spells` SET `description_de` = 'Du beschwörst ein Feenwesen mit HG 6 oder niedriger, oder einen Feengeist, der die Form einer Bestie mit HG 6 oder niedriger annimmt. Es erscheint in einem freien Raum, den du in Reichweite sehen kannst. Das Feenwesen verschwindet, wenn es auf 0 TP fällt oder der Zauber endet. Das Feenwesen ist freundlich dir und deinen Gefährten gegenüber, für die Dauer. Würfle Initiative für das Feenwesen. Es befolgt verbale Befehle, die du ihm gibst (keine Aktion erforderlich). Falls du ihm keinen Befehl gibst, verteidigt es sich, unternimmt aber sonst keine Aktionen. **Auf höheren Stufen:** Der HG erhöht sich um 1 pro Zaubergrad über 6.', `range_de` = '27 m', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Beschwörung' WHERE `id` = 124;

UPDATE `spells` SET `description_de` = 'Du kannalisierst positive Energie, um die Verletzungen einer Kreatur zu heilen. Du berührst eine Kreatur, und sie erhält **70 Trefferpunkte** zurück. Der Zauber beendet auch Blindheit, Taubheit und alle Krankheiten, die die Kreatur befallen. Dieser Zauber hat keine Wirkung auf Untote oder Konstrukte. **Auf höheren Stufen:** +10 TP pro Zaubergrad über 6.', `range_de` = 'Berührung', `duration_de` = 'Unmittelbar', `school_de` = 'Hervorrufung' WHERE `id` = 125;

UPDATE `spells` SET `description_de` = 'Du bringst ein großartiges Fest von exquisitem Essen und Trinken hervor. Das Fest dauert 1 Stunde und verschwindet am Ende dieser Zeit. Die wohltuenden Effekte treten erst in Kraft, wenn diese Stunde abgelaufen ist. Bis zu zwölf Kreaturen können an dem Fest teilnehmen. Eine Kreatur, die an dem Fest teilnimmt, erhält mehrere Vorteile. Die Kreatur wird von allen Krankheiten und Giften geheilt, wird immun gegen Gift und Furcht, und macht alle Weisheitsrettungswürfe mit Vorteil. Ihre maximalen Trefferpunkte erhöhen sich um 2W10, und sie erhält dieselbe Anzahl an Trefferpunkten. Diese Vorteile halten 24 Stunden an.', `range_de` = '9 m', `duration_de` = 'Unmittelbar', `school_de` = 'Beschwörung' WHERE `id` = 126;

UPDATE `spells` SET `description_de` = 'Flammen umhüllen deinen Körper, bis der Zauber endet, und verleihen dir die folgenden Vorteile: Du bist immun gegen Feuerschaden und hast Resistenz gegen Kälteschaden; Du kannst dich durch enge Räume bewegen, als wärst du eine Kreatur von Größe Winzig, ohne zu quetschen; Du wirfst helles Licht in einem Radius von 9 m und dämmriges Licht für weitere 9 m; Jede Kreatur, die dich berührt oder innerhalb von 1,5 m von dir mit einem Nahkampfangriff trifft, erleidet **1W10 Feuerschaden**.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Verwandlung' WHERE `id` = 127;

UPDATE `spells` SET `description_de` = 'Bis der Zauber endet, umgibt dich Eis und verleiht dir die folgenden Vorteile: Du bist immun gegen Kälteschaden und hast Resistenz gegen Feuerschaden; Du kannst dich über schwieriges Gelände bewegen, das aus Eis oder Schnee besteht, ohne zusätzliche Bewegung aufzuwenden; Der Boden in einem Radius von 3 m um dich herum ist vereist und gilt als schwieriges Gelände; Jede Kreatur, die dich berührt oder innerhalb von 1,5 m von dir mit einem Nahkampfangriff trifft, erleidet **2W6 Kälteschaden**; Du kannst deine Aktion einsetzen, um einen Kegel aus gefrorener Luft mit einer Länge von 4,5 m zu erschaffen. Jede Kreatur im Kegel muss einen Konstitutionsrettungswurf bestehen oder **4W6 Kälteschaden** erleiden, oder halb so viel bei Erfolg.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Verwandlung' WHERE `id` = 128;

UPDATE `spells` SET `description_de` = 'Bis der Zauber endet, umfangen dich Gesteinsbrocken und verleihen dir die folgenden Vorteile: Du bist immun gegen Wuchtschaden und hast Resistenz gegen Feuer- und Blitzschaden; Du kannst deine Aktion einsetzen, um einen kleinen Erdbeben auf dem Boden in einem Radius von 4,5 m zu erzeugen, zentriert auf dir. Andere Kreaturen in diesem Bereich müssen einen Geschicklichkeitsrettungswurf bestehen oder umgeworfen werden; Du kannst dich durch schwieriges Gelände aus Erde oder Gestein bewegen, ohne zusätzliche Bewegung aufzuwenden. Du kannst durch festen Stein bewegen, als wäre er schwieriges Gelände. Falls du deinen Zug dort beendest, wirst du ausgestoßen in den nächsten freien Raum, den du zuletzt besetzt hast.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Verwandlung' WHERE `id` = 129;

UPDATE `spells` SET `description_de` = 'Bis der Zauber endet, umgibt dich Wind und verleiht dir die folgenden Vorteile: Fernkampfangriffe gegen dich haben Nachteil; Du hast eine Fluggeschwindigkeit von 18 m. Falls du fliegst, wenn der Zauber endet, fällst du, außer du kannst deinen Fall stoppen; Du kannst deine Aktion einsetzen, um einen Würfel von 4,5 m Kantenlänge aus wirbelndem Wind zu erschaffen, zentriert auf einem Punkt, den du sehen kannst, innerhalb von 18 m von dir. Jede Kreatur in diesem Bereich muss einen Konstitutionsrettungswurf bestehen oder **2W10 Wuchtschaden** erleiden. Eine Kreatur von Größe Mittel oder kleiner, die den Rettungswurf nicht besteht, wird auch bis zu 3 m weggeschoben.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 10 Minuten', `school_de` = 'Verwandlung' WHERE `id` = 130;

UPDATE `spells` SET `description_de` = 'Du verursachst, dass bis zu sechs Säulen aus Stein aus Stellen auf dem Boden herausschießen, die du in Reichweite sehen kannst. Jede Säule ist ein Zylinder mit einem Durchmesser von 1,5 m und einer Höhe von bis zu 9 m. Der Boden, wo eine Säule erscheint, muss breit genug sein, um ihren Durchmesser zu unterstützen, und du kannst eine Säule unter einer Kreatur erscheinen lassen. Falls eine Säule unter einer Kreatur erscheint, muss diese Kreatur einen Geschicklichkeitsrettungswurf bestehen oder von der aufsteigenden Säule getragen werden. Eine Kreatur kann wählen, den Rettungswurf nicht zu bestehen. Falls eine Kreatur, die auf einer Säule steht, nicht in der Lage ist, auf der Säule Platz zu finden, fällt sie von der Säule. Falls eine Säule nicht genug Raum hat, um 9 m zu wachsen, erleidet eine Kreatur auf der Säule **6W6 Wuchtschaden** und wird gegen das feste Objekt gedrückt.', `range_de` = '36 m', `duration_de` = 'Unmittelbar', `school_de` = 'Verwandlung' WHERE `id` = 131;

UPDATE `spells` SET `description_de` = 'Dieser Zauber erschafft ein magisches Verbindungsglied zwischen einer Großen oder größeren unbelebten Pflanze innerhalb der Reichweite und einer anderen Pflanze, egal wie weit entfernt, auf derselben Existenzebene. Du musst beide Pflanzen zuvor gesehen oder berührt haben. Für die Dauer kann jede Kreatur in die Zielpflanze eintreten und aus der Zielpflanze herauskommen, indem sie 1,5 m Bewegung aufwendet.', `range_de` = '3 m', `duration_de` = '1 Runde', `school_de` = 'Beschwörung' WHERE `id` = 132;

UPDATE `spells` SET `description_de` = 'Ein Lichtstrahl von Sonnenlicht strahlt aus deiner Hand in einer Linie mit einer Länge von 18 m und einer Breite von 1,5 m. Jede Kreatur in der Linie muss einen Konstitutionsrettungswurf bestehen oder **6W8 gleißenden Schaden** erleiden und wird geblendet, bis zu deinem nächsten Zug. Bei einem erfolgreichen Rettungswurf erleidet eine Kreatur den halben Schaden und ist nicht geblendet. Untote und Schleime haben Nachteil auf diesem Rettungswurf. Du kannst als Aktion in jedem deiner Züge eine neue Linie aus Licht erschaffen, für die Dauer. Für die Dauer leuchtet ein Punkt mit hellem Licht in deiner Hand in einem Radius von 9 m und dämmrigem Licht für weitere 9 m. Dieses Licht ist Sonnenlicht. **Auf höheren Stufen:** +1W8 Schaden pro Zaubergrad über 6.', `range_de` = 'Selbst (Linie 18 m)', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Hervorrufung' WHERE `id` = 133;

UPDATE `spells` SET `description_de` = 'Du rufst die Ur-Gewalten der Natur herbei, um dich zu beschützen. Für die Dauer erhältst du Resistenz gegen Säure-, Kälte-, Feuer-, Blitz- und Schallschaden. Du kannst deine Aktion in jedem deiner Züge aufwenden, um die Resistenzen zu nutzen, um temporäre Immunität gegen einen dieser Schadenstypen zu erhalten, bis zum Beginn deines nächsten Zuges. In diesem Zug verlierst du aber die Resistenzen gegenüber den anderen vier Schadenstypen.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Bannzauber' WHERE `id` = 134;

UPDATE `spells` SET `description_de` = 'Dieser Zauber ermöglicht es dir, den kürzesten, direktesten physischen Weg zu einem spezifischen festen Ort zu finden, mit dem du vertraut bist und das sich auf derselben Existenzebene befindet. Wenn du einen Zielort benennst, offenbart dir der Zauber den Weg und die Distanz zu diesem Ort, und solange du dich zum Ziel bewegst, wann immer ein Weg zur Verfügung steht, kannst du den direktesten physischen Weg nehmen. Falls du zum Beispiel von einem Zauber immobilisiert oder festgehalten würdest, würde der Zauber neue Informationen offenbaren, die es dir ermöglichen, dich fortzubewegen, während du auf dem Weg bist. Der Zauber endet, wenn du deinen Zielort erreichst, oder wenn du dich an einen Ort bewegst, der auf einer anderen Existenzebene ist.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 1 Tag', `school_de` = 'Erkenntniszauber' WHERE `id` = 135;

UPDATE `spells` SET `description_de` = 'Du und bis zu zehn willige Kreaturen, die du sehen kannst, innerhalb der Reichweite, nehmen gasförmige Gestalt an für die Dauer, erscheinen als wispy Wolken. Während ihr in dieser wolkenartigen Form seid, hat eine betroffene Kreatur eine Fluggeschwindigkeit von 90 m und Resistenz gegen Schaden von nicht-magischen Waffen. Die einzigen Aktionen, die eine betroffene Kreatur in dieser Form ausführen kann, sind die Schussfahrt-Aktion oder das Zurückkehren in ihre normale Form. Das Zurückkehren nimmt 1 Minute in Anspruch, während derer eine Kreatur handlungsunfähig und sich nicht bewegen kann. Bis der Zauber endet, kann eine betroffene Kreatur zwischen ihrer Wolkenform und ihrer normalen Form hin und her wechseln. Eine betroffene Kreatur hat Vorteil auf Rettungswürfen gegen Zauber und andere magische Effekte. Eine betroffene Kreatur in Wolkenform kann durch Kreaturen hindurchgehen, kleine Löcher passieren, enge Öffnungen und sogar bloße Risse.', `range_de` = '9 m', `duration_de` = '8 Stunden', `school_de` = 'Verwandlung' WHERE `id` = 136;

-- ============================================
-- LEVEL 7 ZAUBER - 6 Zauber
-- ============================================

UPDATE `spells` SET `description_de` = 'Du berührst eine tote Kreatur, die nicht länger als ein Jahrhundert tot ist, nicht an Alter gestorben ist und keine Untote ist. Falls ihre Seele frei und willig ist, kehrt die Kreatur mit allen ihren Trefferpunkten zum Leben zurück. Dieser Zauber neutralisiert alle Gifte und heilt normale Krankheiten, die die Kreatur zum Zeitpunkt ihres Todes befallen hatten. Er heilt keine magischen Krankheiten, Flüche und ähnliches; falls diese nicht vor dem Wirken des Zaubers zuerst entfernt werden, befallen sie die Kreatur beim Zurückkehren zum Leben. Dieser Zauber schließt alle tödlichen Wunden und stellt alle fehlenden Körperteile wieder her. Das Zurückkommen aus dem Tod ist eine Belastung. Das Ziel erleidet einen Malus von -4 auf alle Angriffswürfe, Rettungswürfe und Attributswürfe. Jedes Mal, wenn das Ziel eine lange Rast beendet, verringert sich der Malus um 1, bis er verschwindet.', `range_de` = 'Berührung', `duration_de` = 'Unmittelbar', `school_de` = 'Nekromantie' WHERE `id` = 137;

UPDATE `spells` SET `description_de` = 'Du und bis zu acht willige Kreaturen, die sich an den Händen halten und einen Kreis bilden, werden auf eine andere Existenzebene transportiert. Du kannst einen allgemeinen Zielort angeben, wie die Stadt aus Messing auf der Elementarebene des Feuers. Du erscheinst in oder nahe diesem Ziel. Alternativ, falls du die Sequenz eines Sigils-Kreises auf einer anderen Existenzebene kennst, kann dieser Zauber dich zu diesem Kreis bringen. Falls der Sigils-Kreis zu klein ist, um alle Kreaturen aufzunehmen, die du teleportiert hast, erscheinen die zusätzlichen Kreaturen in den nächsten freien Räumen beim Kreis.', `range_de` = 'Berührung', `duration_de` = 'Unmittelbar', `school_de` = 'Beschwörung' WHERE `id` = 138;

UPDATE `spells` SET `description_de` = 'Ein Sturm aus brüllenden Flammen erscheint an einem Ort, den du innerhalb der Reichweite bestimmst. Der Bereich des Sturms besteht aus bis zu zehn Würfeln mit 3 m Kantenlänge, die du anordnen kannst, wie du möchtest. Jeder Würfel muss mindestens eine Fläche mit einem anderen Würfel teilen. Jede Kreatur im Bereich muss einen Geschicklichkeitsrettungswurf bestehen oder **7W10 Feuerschaden** erleiden, oder halb so viel bei Erfolg. Das Feuer entzündet brennbare Objekte im Bereich, die nicht getragen oder gehalten werden. **Auf höheren Stufen:** +1W10 Schaden pro Zaubergrad über 7.', `range_de` = '45 m', `duration_de` = 'Unmittelbar', `school_de` = 'Hervorrufung' WHERE `id` = 139;

UPDATE `spells` SET `description_de` = 'Du berührst eine Kreatur und stimulierst ihre natürliche Heilfähigkeit. Das Ziel erhält **4W8 + 15 Trefferpunkte** zurück. Für die Dauer des Zaubers erhält das Ziel 1 Trefferpunkt zu Beginn jedes seiner Züge (10 TP pro Minute) zurück. Die abgetrennten Körperteile des Ziels (Finger, Beine, Schwänze usw.), falls vorhanden, werden nach 2 Minuten wiederhergestellt. Falls du ein abgetrenntes Körperteil an den Stumpf hältst, verursacht der Zauber, dass es sofort wieder anwächst. **Auf höheren Stufen:** +1W8 anfängliche Heilung + 5 TP pro Zaubergrad über 7.', `range_de` = 'Berührung', `duration_de` = '1 Stunde', `school_de` = 'Verwandlung' WHERE `id` = 140;

UPDATE `spells` SET `description_de` = 'Dieser Zauber kehrt die Schwerkraft in einem Zylinder mit 15 m Radius und 30 m Höhe um, zentriert auf einem Punkt innerhalb der Reichweite. Alle Kreaturen und Objekte, die nicht irgendwie am Boden verankert sind, fallen im Bereich aufwärts und erreichen die Spitze des Bereichs, wenn du diesen Zauber wirkst. Eine Kreatur kann einen Geschicklichkeitsrettungswurf machen, um sich an einem festen Objekt festzuhalten, das sie erreichen kann, und vermeidet so den Sturz. Falls ein festes Objekt (wie eine Decke) im Bereich angetroffen wird, fallen Kreaturen und Objekte dagegen auf, wie sie es würden, wenn sie auf den Boden gefallen wären. Wenn der Zauber endet, fallen alle betroffenen Kreaturen und Objekte nach unten.', `range_de` = '30 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Verwandlung' WHERE `id` = 141;

UPDATE `spells` SET `description_de` = 'Ein Wirbelsturm mit 3 m Radius und 9 m Höhe erscheint an einem Punkt, den du in Reichweite sehen kannst. Bis der Zauber endet, kannst du deine Aktion einsetzen, um den Wirbelsturm bis zu 9 m in jede Richtung entlang des Bodens zu bewegen. Der Wirbelsturm saugt Kreaturen von Größe Riesig oder kleiner an, die nicht am Boden verankert sind und näher als 9 m zum Wirbelsturm sind. Eine Kreatur muss einen Geschicklichkeitsrettungswurf bei der ersten Berührung mit dem Wirbelsturm in einem Zug bestehen. Bei einem Misserfolg betritt eine Kreatur den Wirbelsturm und kann als Aktion versuchen, sich zu befreien (Stärke-Wurf). Wenn eine Kreatur ihren Zug im Wirbelsturm beginnt oder zum ersten Mal in einem Zug den Wirbelsturm betritt, muss sie einen Stärkerettungswurf bestehen oder **10W6 Wuchtschaden** erleiden und wird 3 m im Wirbelsturm nach oben gesogen, falls unter der Spitze. **Auf höheren Stufen:** +2W6 Schaden pro Zaubergrad über 7.', `range_de` = '90 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Hervorrufung' WHERE `id` = 142;

-- ============================================
-- LEVEL 8 ZAUBER - 7 Zauber
-- ============================================

UPDATE `spells` SET `description_de` = 'Du planzt einen starken Widerwillen oder eine starke Anziehung in einem Objekt oder Bereich, den du sehen kannst und der nicht größer ist als ein Würfel von 60 m Kantenlänge. Spezifiziere eine Art von intelligenter Kreatur, wie z.B. rote Drachen, Goblins oder Vampire. Das Gebiet oder Objekt strahlt eine Aura aus, die die angegebene Art von Kreatur anzieht oder abstößt, für die Dauer. Wähle Antipathie oder Sympathie beim Wirken: **Antipathie:** Die Verzauberung verursacht, dass Kreaturen der angegebenen Art eine intensive Dringlichkeit fühlen, das Gebiet zu verlassen und es zu meiden. **Sympathie:** Die Verzauberung verursacht, dass die angegebene Art von Kreaturen einen intensen Wunsch verspürt, sich dem Effekt zu nähern.', `range_de` = '18 m', `duration_de` = '10 Tage', `school_de` = 'Verzauberung' WHERE `id` = 143;

UPDATE `spells` SET `description_de` = 'Du erschaffst ein seismisches Beben an einem Punkt auf dem Boden, den du in Reichweite sehen kannst. Für die Dauer erschüttert ein intensiver Tremor den Boden in einem Kreis mit 30 m Radius, zentriert auf diesem Punkt, und schüttelt Kreaturen und Strukturen in Kontakt mit dem Boden in diesem Bereich. Der Boden im Bereich wird zu schwierigem Gelände. Jede Kreatur auf dem Boden, die sich konzentriert, muss einen Konstitutionsrettungswurf bestehen oder ihre Konzentration verlieren. Wenn du diesen Zauber wirkst und am Ende jedes Zuges, den du damit verbringst, dich darauf zu konzentrieren, muss jede Kreatur auf dem Boden im Bereich einen Geschicklichkeitsrettungswurf bestehen oder zu Boden geworfen werden. Dieser Zauber kann zusätzliche Effekte haben, abhängig vom Gelände: **Spalten:** Spalten öffnen sich im Bereich, am Ende des Zuges, in dem du den Zauber wirkst. Insgesamt öffnen sich 1W6 solche Spalten in Orten, die der SL wählt. Jede ist 1W10 x 3 m tief, 3 m breit. **Strukturen:** Der Tremor verursacht **50 Wuchtschaden** an Strukturen in Kontakt mit dem Boden im Bereich, wenn du den Zauber wirkst und am Anfang jedes deiner Züge, bis der Zauber endet. Falls eine Struktur auf 0 TP fällt, bricht sie zusammen. Eine Kreatur innerhalb von 15 m von einer zusammenbrechenden Struktur muss einen Geschicklichkeitsrettungswurf bestehen oder **5W6 Wuchtschaden** erleiden, zu Boden geworfen werden und unter Trümmern begraben werden. Eine begrabene Kreatur ist festgehalten und kann sich nicht aufstehen oder bewegen.', `range_de` = '150 m', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Hervorrufung' WHERE `id` = 144;

UPDATE `spells` SET `description_de` = 'Du versuchst, die Intelligenz und das Bewusstsein einer Kreatur zu zerbrechen. Das Ziel erleidet **4W6 psychischen Schaden** und muss einen Intelligenzrettungswurf bestehen. Bei einem fehlgeschlagenen Rettungswurf sinkt die Intelligenz und das Charisma der Kreatur auf 1. Die Kreatur kann keine Zauber wirken, keine magischen Gegenstände aktivieren, keine Sprachen verstehen oder auf irgendeine intelligible Weise kommunizieren. Die Kreatur kann aber trotzdem ihre Freunde identifizieren, ihnen folgen und sie sogar beschützen. Am Ende alle 30 Tage kann die Kreatur den Rettungswurf gegen diesen Zauber wiederholen. Falls sie erfolgreich ist, endet der Zauber. Der Zauber kann auch durch Wunden Heilen, Vollständige Genesung, oder einen Wunsch-Zauber beendet werden.', `range_de` = '45 m', `duration_de` = 'Unmittelbar', `school_de` = 'Verzauberung' WHERE `id` = 145;

UPDATE `spells` SET `description_de` = 'Gleißendes Sonnenlicht blitzt in einem Radius von 18 m, zentriert auf einem Punkt, den du innerhalb der Reichweite wählst. Jede Kreatur in diesem Licht muss einen Konstitutionsrettungswurf bestehen oder **12W6 gleißenden Schaden** erleiden und wird geblendet für 1 Minute. Bei Erfolg erleidet sie den halben Schaden und ist nicht geblendet. Untote und Schleime haben Nachteil auf diesem Rettungswurf. Eine Kreatur, die von diesem Zauber geblendet wird, macht am Ende jedes ihrer Züge einen weiteren Konstitutionsrettungswurf. Bei einem erfolgreichen Rettungswurf ist sie nicht länger geblendet. Dieser Zauber zerstreut jede Dunkelheit in seinem Bereich, die durch einen Zauber erschaffen wurde. **Auf höheren Stufen:** +1W6 Schaden pro Zaubergrad über 8.', `range_de` = '45 m', `duration_de` = 'Unmittelbar', `school_de` = 'Hervorrufung' WHERE `id` = 146;

UPDATE `spells` SET `description_de` = 'Deine Magie verwandelt andere in Bestien. Wähle eine beliebige Anzahl von willigen Kreaturen, die du in Reichweite sehen kannst. Du verwandelst jedes Ziel in eine Große oder kleinere Bestie mit einem HG von 4 oder weniger. In nachfolgenden Zügen kannst du deine Aktion einsetzen, um betroffene Kreaturen in neue Formen zu verwandeln. Die neue Form kann jede Bestie sein, die du wählst, mit einem HG gleich oder kleiner 4. Die Verwandlung hält für die Dauer für jede Kreatur an, oder bis die Kreatur auf 0 TP fällt oder stirbt. Die Spielwerte jedes Ziels werden durch die Statistiken der gewählten Bestie ersetzt. Das Ziel behält aber seine Gesinnung und Persönlichkeit. **Auf höheren Stufen:** +1 maximaler HG pro Zaubergrad über 8.', `range_de` = '9 m', `duration_de` = 'Konzentration, bis zu 24 Stunden', `school_de` = 'Verwandlung' WHERE `id` = 147;

UPDATE `spells` SET `description_de` = 'Eine Wand aus Wasser springt aus einem Punkt auf dem Boden hervor, den du innerhalb der Reichweite wählst. Du kannst die Wand bis zu 90 m lang, 90 m hoch und 15 m dick machen. Die Wand hält für die Dauer an. Wenn die Wand erscheint, muss jede Kreatur innerhalb ihres Bereichs einen Stärkerettungswurf bestehen oder **6W10 Wuchtschaden** erleiden, oder halb so viel bei Erfolg. Am Anfang jedes deiner Züge, nach dem Erscheinen der Wand, bewegt sich die Wand 15 m von dir weg, zusammen mit jedem in ihr befindlichen Geschöpf. Jede Riesige oder kleinere Kreatur innerhalb der Wand oder deren Raum die Wand durchquert, wenn sie sich bewegt, muss einen Stärkerettungswurf bestehen oder **5W10 Wuchtschaden** erleiden. Eine Kreatur kann diesen Schaden nur einmal pro Runde erleiden. Am Ende des Zuges fällt die Höhe der Wand um 15 m, und der Schaden, den Kreaturen im nächsten Zug erleiden, verringert sich um 1W10. Wenn die Höhe der Wand auf 0 m fällt, endet der Zauber. Eine Kreatur, die in der Wand gefangen ist, kann sich schwimmend bewegen, aber die Wand ist so schwierig, dass die Kreatur für jeden 1,5 m, den sie schwimmt, 6 m Bewegung aufwenden muss.', `range_de` = '150 m', `duration_de` = 'Konzentration, bis zu 6 Runden', `school_de` = 'Beschwörung' WHERE `id` = 148;

UPDATE `spells` SET `description_de` = 'Du übernimmst die Kontrolle über das Wetter innerhalb von 8 km von dir für die Dauer. Du musst im Freien sein, um diesen Zauber zu wirken. Dich an einen Ort zu bewegen, wo du keinen klaren Pfad zum Himmel hast, beendet den Zauber vorzeitig. Wenn du den Zauber wirkst, änderst du die aktuellen Wetterbedingungen, die vom SL basierend auf Klima und Jahreszeit bestimmt werden. Du kannst Niederschlag, Temperatur und Wind ändern. Es dauert 1W4 x 10 Minuten, bis die neuen Bedingungen wirksam werden. Sobald sie dies tun, kannst du die Bedingungen wieder ändern. Wenn der Zauber endet, kehrt das Wetter allmählich zu den normalen Bedingungen zurück. Wenn du die Bedingungen änderst, finde eine aktuelle Bedingung in der folgenden Tabelle und ändere ihre Stufe um eins, nach oben oder unten. Beispielkategorien: **Niederschlag** (klar, leicht bewölkt, überwölkt, Regen/Schnee, Sturm); **Temperatur** (unerträgliche Hitze, heiß, warm, kühl, kalt, arktische Kälte); **Wind** (windstill, mäßiger Wind, starker Wind, Sturm, Orkan).', `range_de` = 'Selbst (Radius 8 km)', `duration_de` = 'Konzentration, bis zu 8 Stunden', `school_de` = 'Verwandlung' WHERE `id` = 149;

-- ============================================
-- LEVEL 9 ZAUBER - 4 Zauber
-- ============================================

UPDATE `spells` SET `description_de` = 'Du nimmst die Form einer anderen Kreatur für die Dauer an. Die neue Form kann jede Kreatur mit einem HG sein, der gleich deiner Stufe oder niedriger ist. Die Kreatur darf kein Konstrukt oder Untoter sein, und du musst die Art der Kreatur mindestens einmal gesehen haben. Du verwandelst dich in ein durchschnittliches Exemplar dieser Kreatur, eines ohne Klassenstufen und ohne das Merkmal Zauberwirken. Deine Spielwerte werden durch die Statistiken der gewählten Kreatur ersetzt, obwohl du deine Gesinnung und deine Intelligenz-, Weisheits- und Charismawerte beibehältst. Du behältst auch alle Fertigkeiten und Rettungswurf-Beherrschungen, zusätzlich zu denen der Kreatur. Wenn die Kreatur dieselbe Beherrschung wie du hat und der Bonus im Stat-Block ihrer Kreatur höher ist als deiner, verwende den Bonus der Kreatur anstelle von deinem. Du kannst deine Aktion einsetzen, um deine Form in eine andere Form anzunehmen, die die Anforderungen und Einschränkungen dieses Zaubers erfüllt. Die neuen Formen müssen keinen Zusammenhang mit der vorherigen Form haben.', `range_de` = 'Selbst', `duration_de` = 'Konzentration, bis zu 1 Stunde', `school_de` = 'Verwandlung' WHERE `id` = 150;

UPDATE `spells` SET `description_de` = 'Eine brüllende Wolke erscheint in der Form eines Zylinders mit einer Höhe von 108 m und einem Radius von 108 m, zentriert auf einem Punkt, den du sehen kannst, 300 m direkt über dir. Der Zauber schlägt fehl, falls du keinen Himmel über dir sehen kannst (zum Beispiel, wenn du in einem Dungeon bist). Wenn du den Zauber wirkst, wähle zwei der folgenden Effekte. Der Zauber dauert 1 Minute, und in jeder Runde in deinem Zug tritt ein neuer Effekt ein (Runden 1-2, 3-4, 5-9, 10): **Runde 2:** Säureregen fällt. Jede Kreatur und jedes Objekt im Bereich erleidet **2W8 Säureschaden**. **Runde 3-4:** Du rufst sechs Blitze aus der Wolke herbei, um sechs Kreaturen oder Objekte deiner Wahl im Bereich zu treffen. Eine gegebene Kreatur oder Objekt kann nicht von mehr als einem Blitz getroffen werden. Eine getroffene Kreatur muss einen Geschicklichkeitsrettungswurf bestehen oder **10W6 Blitzschaden** erleiden, oder halb so viel bei Erfolg. **Runde 5-6:** Eisige Hagelkörner fallen. Jede Kreatur im Bereich erleidet **2W6 Wuchtschaden**. **Runde 7-8:** Böige Winde und Regen wehen durch den Bereich. Der Bereich wird schwieriges Gelände, und Fernkampf-Waffenangriffe sind unmöglich. Der Wind und der Regen zählen als schwere Verschleierung. **Runde 9-10:** Gewalttätiger Regen und Wind peitsche

n den Bereich. Jede Kreatur im Bereich erleidet **2W6 Wuchtschaden**. Die Hagelkörner verwandeln den Boden des Bereichs in schwieriges Gelände, bis zum Ende deines nächsten Zuges. **Runde 10:** Du wirst von 200-300 Hagel-Asteroiden bombardiert, die in den Bereich einschlagen. Jede Kreatur im Bereich muss einen Geschicklichkeitsrettungswurf bestehen oder **2W6 Wuchtschaden** von den fallenden Hagelkörnern erleiden.', `range_de` = 'Sichtweite', `duration_de` = 'Konzentration, bis zu 1 Minute', `school_de` = 'Beschwörung' WHERE `id` = 151;

UPDATE `spells` SET `description_de` = 'Du berührst eine willige Kreatur und verleihst ihr eine begrenzte Fähigkeit, in die Zukunft zu sehen. Für die Dauer kann das Ziel nicht überrascht werden und hat Vorteil auf Angriffswürfe, Attributswürfe und Rettungswürfe. Zusätzlich haben andere Kreaturen Nachteil auf Angriffswürfe gegen das Ziel für die Dauer. Dieser Zauber endet sofort, falls du ihn erneut wirkst, bevor seine Dauer abläuft.', `range_de` = 'Berührung', `duration_de` = '8 Stunden', `school_de` = 'Erkenntniszauber' WHERE `id` = 152;

UPDATE `spells` SET `description_de` = 'Du berührst eine Kreatur, die seit nicht mehr als 200 Jahren tot ist und die nicht an Altersschwäche gestorben ist. Falls die Seele der Kreatur frei und willig ist, wird die Kreatur mit allen ihren Trefferpunkten wiederbelebt. Dieser Zauber schließt alle Wunden, neutralisiert alle Gifte, heilt alle Krankheiten und hebt alle Flüche auf, die die Kreatur zum Zeitpunkt ihres Todes befielen. Der Zauber ersetzt beschädigte oder fehlende Organe und Gliedmaßen. Falls die Kreatur untot war, wird sie in ihren nicht-untoten Zustand wiederhergestellt. Der Zauber kann sogar einen neuen Körper erschaffen, falls der ursprüngliche Körper nicht mehr existiert, in welchem Fall du den Namen der Kreatur aussprechen musst. Die Kreatur erscheint dann in einem freien Raum, den du innerhalb von 3 m von dir wählst.', `range_de` = 'Berührung', `duration_de` = 'Unmittelbar', `school_de` = 'Nekromantie' WHERE `id` = 153;

-- ============================================
-- FERTIG! Alle 153 Zauber sind jetzt vollständig beschrieben
-- ============================================
